### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by awxiaoxian2020** [awxiaoxian2020/vitepress#1]
VitePress 中文文档翻译讨论。

**Comment by awxiaoxian2020** [comment]
@shellRaining 我们在这里讨论相关事项。

**Comment by shellRaining** [comment]
我们在翻译的过程中需要遵守什么守则吗（类似[Vue 中文翻译须知](https://github.com/vuejs-translations/docs-zh-cn/wiki/%E7%BF%BB%E8%AF%91%E9%A1%BB%E7%9F%A5)），还是等后期一并修改呢

**Comment by awxiaoxian2020** [comment]
我们遵从 Vue 中文翻译原则~

**Comment by shellRaining** [comment]
好的，那麻烦您分配一下翻译任务？

**Comment by awxiaoxian2020** [comment]
你准备先翻译哪一篇，为了避免撞车，在这里说一下吧，随时跟踪进展~

**Comment by shellRaining** [comment]
markdown 拓展那篇还有一部分没有翻译完，我想先把那个补全

**Comment by awxiaoxian2020** [comment]
好的~

**Comment by shellRaining** [comment]
我刚才提交上去了 `Markdown 扩展` 这部分。有一些名词不太会翻译，比方说 `Errors and Warnings in Code Blocks`，我暂时翻译成 `代码块中的 Errors 和 Warnings 高亮`，还有 `Code Groups`，翻译成了 `代码组`，感觉很生硬。

**Comment by awxiaoxian2020** [comment]
我个人认为 `代码组` 没有问题。因为有 `代码块` 的说法。`Errors and Warnings in Code Blocks` 建议翻译为 `高亮“警告”和“错误”`。
感谢你的付出和贡献！

**Comment by shellRaining** [comment]
好的，我回去改一下。今天晚上我打算翻译一下资源管理

**Comment by shellRaining** [comment]
资源处理部分翻译完成，之后翻译 frontmatter。我们需不需要制定一个认领任务的表格（类似于[📒 【认领】翻译任务认领说明](https://github.com/eslint/cn.eslint.org/issues/34)）呢，这样应该不会让这个 issue 变得难以理清

**Comment by awxiaoxian2020** [comment]
> 资源处理部分翻译完成，之后翻译 frontmatter。我们需不需要制定一个认领任务的表格（类似于[📒 【认领】翻译任务认领说明](https://github.com/eslint/cn.eslint.org/issues/34)）呢，这样应该不会让这个 issue 变得难以理清

因为就我们两个人，所以我觉得就简单说一声就好~

**Comment by shellRaining** [comment]
frontmatter 部分和 i18n 部分翻译完成。有一些小问题，比如 frontmatter 的具体翻译，还有不太了解为什么原文档 i18n 部分最后一段不使用 markdown 的链接语法。

**Comment by awxiaoxian2020** [comment]
> 

frontmatter 好像是 VitePress 特有的概念。翻译可能会有误解吧，你有什么好的建议吗？一切先按原文档来~

**Comment by shellRaining** [comment]
名词翻译暂时没有好的想法。
我先按照源仓库翻译，之后会在那边提一下。
今天翻译任务是 `自定义主题` 和 `拓展默认主题`

**Comment by shellRaining** [comment]
这两章节翻译完毕，之后大概每天翻译一章节，预计周五翻译完指南部分~

**Comment by shellRaining** [comment]
~~指南部分翻译完毕~~ 还漏了路由和部署部分，不过因为 SSR 兼容和 mpa 模式我也没有用过，翻译内容可能出现错误，我打算之后一周重新看一下翻译的内容，有错误或者不确定的地方会标出 TODO 来方便商量一下。有时间我会翻译一下路由和部署章节。

**Comment by awxiaoxian2020** [comment]
我准备翻译参考部分

**Comment by shellRaining** [comment]
OK。我有一个疑问，如果英文版本的手册部分更新了，我们中文版该怎么跟进呢，我想如果一直盯着commit信息似乎也不是很容易

**Comment by awxiaoxian2020** [comment]
> OK。我有一个疑问，如果英文版本的手册部分更新了，我们中文版该怎么跟进呢，我想如果一直盯着commit信息似乎也不是很容易

按照通常的情况来说，应该将翻译部分独立出来，放在另一个仓库，然后使用 bot 或者其他手段进行维护。但是这份文档恰好是 VitePress 的文档，放在原仓库可以恰好体现其可国际化特性作一个范例，所以……更新的事情以后再说吧。先把这个 PR 弄好。

参见 https://github.com/vuejs/pinia/discussions/2097 
https://github.com/vuejs-translations/docs-zh-cn/discussions/561
